"""Tests for the requirements.lock drift guard.

Why this exists: `langfuse==2.60.3` sat in requirements.txt while being ABSENT
from requirements.lock. docker/Dockerfile installs only from the lock, with
--require-hashes, so the container never contained langfuse — and
utils/observability.py imports it inside a broad `except`, so instead of failing
loudly the tracing client just returned None. Nothing in CI noticed.

DESIGN NOTE — why containment and not a regeneration diff. The obvious check is
"re-run pip-compile and fail if the output differs". That check goes red the day
any transitive dependency publishes a new release, with zero repo changes,
because the resolver picks up the newer version. It would train everyone to
ignore it. Containment — every pin in requirements.txt appears at the same
version in requirements.lock — is deterministic, involves no resolver, and
catches the failure mode that actually happened.
"""

import pytest

from scripts import check_lock_sync as cls


# ---------------------------------------------------------------------------
# name normalization (PEP 503)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("Pillow", "pillow"),
        ("python_jose", "python-jose"),
        ("ruamel.yaml", "ruamel-yaml"),
        ("PyYAML", "pyyaml"),
    ],
)
def test_canonicalizes_names(raw, expected):
    assert cls.canon(raw) == expected


# ---------------------------------------------------------------------------
# parsing requirements.txt
# ---------------------------------------------------------------------------


def test_parses_simple_pins():
    text = "fastapi==0.135.1\nredis==5.2.1\n"
    assert cls.parse_requirements(text) == {"fastapi": "0.135.1", "redis": "5.2.1"}


def test_ignores_comments_and_blanks():
    text = "# a comment\n\nfastapi==0.135.1   # trailing comment\n"
    assert cls.parse_requirements(text) == {"fastapi": "0.135.1"}


def test_strips_extras():
    """`uvicorn[standard]==0.34.3` pins the package `uvicorn`."""
    text = "uvicorn[standard]==0.34.3\npython-jose[cryptography]==3.4.0\n"
    parsed = cls.parse_requirements(text)
    assert parsed == {"uvicorn": "0.34.3", "python-jose": "3.4.0"}


def test_skips_include_lines():
    """`-r requirements.txt` is an include, not a pin — the included file is
    checked on its own."""
    text = "-r requirements.txt\nPillow==12.3.0\n"
    assert cls.parse_requirements(text) == {"pillow": "12.3.0"}


def test_skips_non_pinned_requirements():
    """Only `==` pins are checkable; a range says nothing about the lock."""
    text = "somepkg>=1.0\nother~=2.0\nexact==3.0\n"
    assert cls.parse_requirements(text) == {"exact": "3.0"}


# ---------------------------------------------------------------------------
# parsing requirements.lock (hash-pinned, backslash continuations)
# ---------------------------------------------------------------------------


def test_parses_lock_entries_with_hashes():
    text = (
        "aiohttp==3.14.3 \\\n"
        "    --hash=sha256:aaa \\\n"
        "    --hash=sha256:bbb\n"
        "    # via -r requirements.txt\n"
        "cryptography==50.0.0 \\\n"
        "    --hash=sha256:ccc\n"
    )
    assert cls.parse_lock(text) == {"aiohttp": "3.14.3", "cryptography": "50.0.0"}


def test_lock_parser_ignores_hash_and_comment_lines():
    text = "# generated by pip-compile\nflask==3.1.3 \\\n    --hash=sha256:ddd\n"
    assert cls.parse_lock(text) == {"flask": "3.1.3"}


# ---------------------------------------------------------------------------
# drift detection — the actual guard
# ---------------------------------------------------------------------------


def test_no_drift_when_lock_contains_every_pin():
    reqs = {"fastapi": "0.135.1", "redis": "5.2.1"}
    lock = {"fastapi": "0.135.1", "redis": "5.2.1", "starlette": "1.0.0"}
    assert cls.find_drift(reqs, lock) == []


def test_extra_packages_in_lock_are_fine():
    """The lock legitimately contains transitive deps the top file never names."""
    assert cls.find_drift({"fastapi": "0.135.1"}, {"fastapi": "0.135.1", "anyio": "4.13.0"}) == []


def test_detects_package_missing_from_lock():
    """The langfuse case, exactly."""
    drift = cls.find_drift({"langfuse": "2.60.3"}, {"fastapi": "0.135.1"})
    assert len(drift) == 1
    assert "langfuse" in drift[0]
    assert "missing" in drift[0].lower()


def test_detects_version_mismatch():
    drift = cls.find_drift({"cryptography": "50.0.0"}, {"cryptography": "48.0.1"})
    assert len(drift) == 1
    assert "50.0.0" in drift[0] and "48.0.1" in drift[0]


def test_reports_every_problem_not_just_the_first():
    drift = cls.find_drift(
        {"a": "1.0", "b": "2.0", "c": "3.0"}, {"a": "9.9"}
    )
    assert len(drift) == 3


# ---------------------------------------------------------------------------
# the real repo files — this is the regression guard itself
# ---------------------------------------------------------------------------


def test_repo_requirements_and_lock_are_in_sync():
    """The guard, run against the actual files. Fails if anyone adds a pin to
    requirements.txt without regenerating requirements.lock."""
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    reqs = cls.parse_requirements((root / "requirements.txt").read_text())
    lock = cls.parse_lock((root / "requirements.lock").read_text())
    drift = cls.find_drift(reqs, lock)
    assert drift == [], (
        "requirements.lock is out of sync with requirements.txt. "
        "Regenerate it with:\n  pip-compile --allow-unsafe --generate-hashes "
        "--output-file=requirements.lock requirements.txt\nDrift:\n  "
        + "\n  ".join(drift)
    )


def test_requirements_txt_is_non_trivial():
    """Guard against the guard passing because a parser bug returned {}."""
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    reqs = cls.parse_requirements((root / "requirements.txt").read_text())
    assert len(reqs) > 20, f"parser found only {len(reqs)} pins — parser bug?"
    assert "fastapi" in reqs and "langfuse" in reqs
