"""CATEGORY_PATTERNS — bilingual offensive-language regex source strings.

Extracted verbatim from the former safety/patterns.py.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

# ============================================================================
# Pattern definitions (English + Spanish)
# ============================================================================

# Each entry is (regex_string, human_description).
# Patterns are matched against the *lightly normalised* form.

CATEGORY_PATTERNS: Dict[str, List[Tuple[str, str]]] = {
    # =================================================================
    # HATE_SPEECH — racial, ethnic, gender, orientation slurs
    # =================================================================
    "HATE_SPEECH": [
        # -- English racial / ethnic slurs --
        (r"\bn[i1l][g9]+[aer3]+s?\b", "racial slur (EN)"),
        (r"\bcoon\b", "racial slur (EN)"),
        (r"\bdarkie\b", "racial slur (EN)"),
        (r"\bjigaboo\b", "racial slur (EN)"),
        (r"\bjiggaboo\b", "racial slur (EN)"),
        (r"\bporch\s*monkey\b", "racial slur (EN)"),
        (r"\bspook\b", "racial slur (EN)"),
        (r"\bspear\s*chucker\b", "racial slur (EN)"),
        (r"\bspic\b", "ethnic slur (EN)"),
        (r"\bspick\b", "ethnic slur (EN)"),
        (r"\bchink\b", "ethnic slur (EN)"),
        (r"\bgook\b", "ethnic slur (EN)"),
        (r"\bslant\s*eye\b", "ethnic slur (EN)"),
        (r"\bzipper\s*head\b", "ethnic slur (EN)"),
        (r"\bwetback\b", "ethnic slur (EN)"),
        (r"\bbeaner\b", "ethnic slur (EN)"),
        (r"\bgringo\b", "ethnic slur (EN)"),
        (r"\bkike\b", "antisemitic slur (EN)"),
        (r"\bheeb\b", "antisemitic slur (EN)"),
        (r"\bjew\s*boy\b", "antisemitic slur (EN)"),
        (r"\bsandnigg\w*\b", "racial slur (EN)"),
        (r"\btowelhead\b", "ethnic slur (EN)"),
        (r"\brag\s*head\b", "ethnic slur (EN)"),
        (r"\bcamel\s*jockey\b", "ethnic slur (EN)"),
        (r"\bpaki\b", "ethnic slur (EN)"),
        (r"\baborigine\b", "ethnic slur (EN)"),
        (r"\babo\b", "ethnic slur (EN)"),
        (r"\bhalf\s*breed\b", "racial slur (EN)"),
        (r"\bmixed\s*breed\b", "racial slur (EN)"),
        (r"\bcracker\b", "racial slur (EN)"),
        (r"\bwhite\s*trash\b", "racial slur (EN)"),
        (r"\bredneck\b", "derogatory (EN)"),
        (r"\bhillbilly\b", "derogatory (EN)"),
        (r"\bredskin\b", "ethnic slur (EN)"),
        (r"\bsquaw\b", "ethnic slur (EN)"),
        (r"\bwop\b", "ethnic slur (EN)"),
        (r"\bdago\b", "ethnic slur (EN)"),
        (r"\bguinea\b", "ethnic slur (EN)"),
        (r"\bpolack\b", "ethnic slur (EN)"),
        (r"\bgypsy\b", "ethnic slur (EN)"),
        (r"\bpikey\b", "ethnic slur (EN)"),
        # -- English gender / orientation slurs --
        (r"\bfagg?ot\w*\b", "orientation slur (EN)"),
        (r"\bfag\b", "orientation slur (EN)"),
        (r"\bdyke\b", "orientation slur (EN)"),
        (r"\blesbo\b", "orientation slur (EN)"),
        (r"\btranny\b", "transphobic slur (EN)"),
        (r"\bshemale\b", "transphobic slur (EN)"),
        (r"\btrapboy\b", "transphobic slur (EN)"),
        (r"\bhe\s*she\b", "transphobic slur (EN)"),
        (r"\bwhore\b", "gender slur (EN)"),
        (r"\bcunt\b", "gender slur (EN)"),
        (r"\bslut\b", "gender slur (EN)"),
        (r"\bskank\b", "gender slur (EN)"),
        (r"\bhoe\b", "gender slur (EN)"),
        (r"\bhoebag\b", "gender slur (EN)"),
        (r"\bfemoid\b", "misogynist slur (EN)"),
        (r"\bthot\b", "gender slur (EN)"),
        (r"\bincel\b", "misogynist term (EN)"),
        (r"\bsimp\b", "derogatory (EN)"),
        # -- Supremacist / hate group references --
        (r"\bwhite\s*power\b", "supremacist term (EN)"),
        (r"\bwhite\s*suprem\w*\b", "supremacist term (EN)"),
        (r"\bwhite\s*pride\b", "supremacist term (EN)"),
        (r"\b(heil|sieg)\s*heil\b", "Nazi reference (EN)"),
        (r"\b14\s*88\b", "hate symbol"),
        (r"\b1488\b", "hate symbol"),
        (r"\bnazi\w*\b", "Nazi reference (EN)"),
        (r"\bhitler\b", "Nazi reference (EN)"),
        (r"\breich\b", "Nazi reference (EN)"),
        (r"\bgestapo\b", "Nazi reference (EN)"),
        (r"\bswastika\b", "Nazi reference (EN)"),
        (r"\baryan\s*nation\b", "supremacist term (EN)"),
        (r"\baryan\s*race\b", "supremacist term (EN)"),
        (r"\baryan\s*brotherhood\b", "supremacist term (EN)"),
        (r"\bkkk\b", "hate group (EN)"),
        (r"\bku\s*klux\b", "hate group (EN)"),
        (r"\bklans\w*\b", "hate group (EN)"),
        (r"\bskin\s*head\b", "hate group (EN)"),
        (r"\bneonazi\b", "hate group (EN)"),
        # -- Spanish racial / ethnic / orientation slurs --
        (r"\bnegro\s+de\s+mierda\b", "racial slur (ES)"),
        (r"\bnegro\s+(sucio|cochino|asqueroso|inmundo)\b", "racial slur (ES)"),
        (r"\bsudaca\b", "ethnic slur (ES)"),
        (r"\bmaric[oó]n\w*\b", "orientation slur (ES)"),
        (r"\bmarica\b", "orientation slur (ES)"),
        (r"\bjoto\w*\b", "orientation slur (ES)"),
        (r"\bpuñal\b", "orientation slur (ES)"),
        (r"\bafeminado\b", "orientation slur (ES)"),
        (r"\bmachorra\b", "orientation slur (ES)"),
        (r"\btortillera\b", "orientation slur (ES)"),
        (r"\bindio\s*(mugroso|sucio|ignorante|bruto)\b", "ethnic slur (ES)"),
        (r"\bnaco\b", "ethnic slur (ES)"),
        (r"\bgabacho\b", "ethnic slur (ES)"),
        (r"\bgringo\s*(sucio|cochino|asqueroso)\b", "ethnic slur (ES)"),
        (r"\bcholo\b", "ethnic slur (ES)"),
        (r"\bmayate\b", "racial slur (ES)"),
        (r"\bprieto\b", "racial slur (ES)"),
        (r"\bchango\b", "racial slur (ES)"),
        (r"\bsimio\b", "racial slur (ES)"),
        (r"\bmono\s+(sucio|asqueroso)\b", "racial slur (ES)"),
    ],
    # =================================================================
    # SEXUAL_CONTENT — explicit, pornographic, vulgar sexual terms
    # =================================================================
    "SEXUAL_CONTENT": [
        # -- English --
        (r"\bporn\w*\b", "explicit term (EN)"),
        (r"\bxxx\b", "explicit term (EN)"),
        (r"\bhentai\b", "explicit term (EN)"),
        (r"\bmilf\b", "explicit term (EN)"),
        (r"\bdilf\b", "explicit term (EN)"),
        (r"\bgilf\b", "explicit term (EN)"),
        (r"\bcocksucker\b", "explicit term (EN)"),
        (r"\bcock\b", "explicit term (EN)"),
        (r"\bfuck\w*\b", "profanity (EN)"),
        (r"\bmasturbat\w*\b", "explicit term (EN)"),
        (r"\borgasm\w*\b", "explicit term (EN)"),
        (r"\bsexting\b", "explicit term (EN)"),
        (r"\bdick(s|head|face)?\b", "explicit term (EN)"),
        (r"\bpussy\b", "explicit term (EN)"),
        (r"\bvagina\b", "explicit term (EN)"),
        (r"\bpenis\b", "explicit term (EN)"),
        (r"\bboobs?\b", "explicit term (EN)"),
        (r"\btits?\b", "explicit term (EN)"),
        (r"\btitties\b", "explicit term (EN)"),
        (r"\berotic\w*\b", "explicit term (EN)"),
        (r"\bnude[sz]?\b", "explicit term (EN)"),
        (r"\bnaked\b", "explicit term (EN)"),
        (r"\bcum\b", "explicit term (EN)"),
        (r"\bcumshot\b", "explicit term (EN)"),
        (r"\bjizz\b", "explicit term (EN)"),
        (r"\bblowjob\b", "explicit term (EN)"),
        (r"\bhandjob\b", "explicit term (EN)"),
        (r"\brape\b", "explicit term (EN)"),
        (r"\brapist\b", "explicit term (EN)"),
        (r"\bmolest\w*\b", "explicit term (EN)"),
        (r"\bpedophil\w*\b", "explicit term (EN)"),
        (r"\bsodom\w*\b", "explicit term (EN)"),
        (r"\banal\b", "explicit term (EN)"),
        (r"\bbondage\b", "explicit term (EN)"),
        (r"\bfetish\b", "explicit term (EN)"),
        (r"\bdominatrix\b", "explicit term (EN)"),
        (r"\bstripper\b", "explicit term (EN)"),
        (r"\bescort\b", "explicit term (EN)"),
        (r"\bhooker\b", "explicit term (EN)"),
        (r"\bprostitut\w*\b", "explicit term (EN)"),
        (r"\bpimp\b", "explicit term (EN)"),
        (r"\bboner\b", "explicit term (EN)"),
        (r"\bhorny\b", "explicit term (EN)"),
        (r"\bbukkake\b", "explicit term (EN)"),
        (r"\bcreampie\b", "explicit term (EN)"),
        (r"\bdoggy\s*style\b", "explicit term (EN)"),
        (r"\bdeepthroat\b", "explicit term (EN)"),
        (r"\bgang\s*bang\b", "explicit term (EN)"),
        (r"\borgy\b", "explicit term (EN)"),
        (r"\bthreesome\b", "explicit term (EN)"),
        (r"\bsex\s*slave\b", "explicit term (EN)"),
        (r"\bclitoris\b", "explicit term (EN)"),
        (r"\bejaculat\w*\b", "explicit term (EN)"),
        (r"\bqueef\b", "explicit term (EN)"),
        (r"\bsmegma\b", "explicit term (EN)"),
        # -- Spanish --
        (r"\bporno\w*\b", "explicit term (ES)"),
        (r"\bverga\b", "explicit term (ES)"),
        (r"\bchingar\w*\b", "profanity (ES)"),
        (r"\bchingad[ao]\b", "profanity (ES)"),
        (r"\btetas\b", "explicit term (ES)"),
        (r"\bchichis?\b", "explicit term (ES)"),
        (r"\bmamada\b", "explicit term (ES)"),
        (r"\bfollar\b", "explicit term (ES)"),
        (r"\bpolla\b", "explicit term (ES)"),
        (r"\bpene\b", "explicit term (ES)"),
        (r"\bculo\b", "explicit term (ES)"),
        (r"\bcoger\b", "explicit term (ES)"),
        (r"\bcog(ida|ido)\b", "explicit term (ES)"),
        (r"\bcaliente\b", "explicit term (ES)"),
        (r"\bcachond[ao]\b", "explicit term (ES)"),
        (r"\bviola(dor|cion)\b", "explicit term (ES)"),
        (r"\bviolar\b", "explicit term (ES)"),
        (r"\bprostitu\w*\b", "explicit term (ES)"),
        (r"\bramera\b", "explicit term (ES)"),
        (r"\bzorra\b", "explicit term (ES)"),
        (r"\bgolfa\b", "explicit term (ES)"),
        (r"\bpiruja\b", "explicit term (ES)"),
        (r"\bpedofil\w*\b", "explicit term (ES)"),
        (r"\borgasmo\b", "explicit term (ES)"),
        (r"\bnalgas\b", "explicit term (ES)"),
        (r"\bpanocha\b", "explicit term (ES)"),
        (r"\bpaloma\b", "explicit term (ES)"),
    ],
    # =================================================================
    # VIOLENCE
    # =================================================================
    "VIOLENCE": [
        (
            r"\bhurt\s+(someone|people|them|him|her|a\s+person)\b",
            "violence intent (EN)",
        ),
        (r"\bkill(er|ing|s)?\b", "violence term (EN)"),
        (r"\bmurder(er|ous|ing|s)?\b", "violence term (EN)"),
        (r"\bschoolshoot\w*\b", "violence term (EN)"),
        (r"\bmass\s*murder\w*\b", "violence term (EN)"),
        (r"\bmass\s*shoot\w*\b", "violence term (EN)"),
        (r"\bserial\s*kill\w*\b", "violence term (EN)"),
        (r"\bgenocide\b", "violence term (EN)"),
        (r"\bterroris[mt]\w*\b", "violence term (EN)"),
        (r"\bjihad\w*\b", "violence term (EN)"),
        (r"\bbehead(ing)?\b", "violence term (EN)"),
        (r"\btortur(e|ing|er)\b", "violence term (EN)"),
        (r"\bbloodbath\b", "violence term (EN)"),
        (r"\bbloodlust\b", "violence term (EN)"),
        (r"\bshooter\b", "violence term (EN)"),
        (r"\bstab(ber|bing|bed)?\b", "violence term (EN)"),
        (r"\bstrangle\b", "violence term (EN)"),
        (r"\bsmother\b", "violence term (EN)"),
        (r"\bslaught\w*\b", "violence term (EN)"),
        (r"\bmassacre\b", "violence term (EN)"),
        (r"\bexecut(e|ion|ioner)\b", "violence term (EN)"),
        (r"\blynch(ing|ed)?\b", "violence term (EN)"),
        (r"\bhomicid\w*\b", "violence term (EN)"),
        (r"\bmanslaughter\b", "violence term (EN)"),
        (r"\barson(ist)?\b", "violence term (EN)"),
        (r"\bbomb(er|ing)?\b", "violence term (EN)"),
        (r"\bexplosi\w*\b", "violence term (EN)"),
        (r"\bgore\b", "violence term (EN)"),
        (r"\bsnuff\b", "violence term (EN)"),
        (r"\bdismember\w*\b", "violence term (EN)"),
        (r"\bmutilat\w*\b", "violence term (EN)"),
        (r"\bskin\s*alive\b", "violence term (EN)"),
        (r"\bdie\b", "violence term (EN)"),
        (r"\bdeath\b", "violence term (EN)"),
        (r"\bdead\s*body\b", "violence term (EN)"),
        (r"\bcorpse\b", "violence term (EN)"),
        (r"\bbleed\s*out\b", "violence term (EN)"),
        (r"\bgun\s*man\b", "violence term (EN)"),
        (r"\bhostage\b", "violence term (EN)"),
        (r"\bkidnap\w*\b", "violence term (EN)"),
        (r"\bassault\b", "violence term (EN)"),
        (r"\bbatter\w*\b", "violence term (EN)"),
        # -- Spanish --
        (r"\bmatar\b", "violence term (ES)"),
        (r"\bmatanza\b", "violence term (ES)"),
        (r"\basesina[rt]\w*\b", "violence term (ES)"),
        (r"\basesino\b", "violence term (ES)"),
        (r"\basesinato\b", "violence term (ES)"),
        (r"\bmasacre\b", "violence term (ES)"),
        (r"\bterrorista\b", "violence term (ES)"),
        (r"\bdecapitar\b", "violence term (ES)"),
        (r"\btortura\w*\b", "violence term (ES)"),
        (r"\bbalacera\b", "violence term (ES)"),
        (r"\bsicario\b", "violence term (ES)"),
        (r"\bnarco\w*\b", "violence term (ES)"),
        (r"\bmuerte\b", "violence term (ES)"),
        (r"\bmuerto\b", "violence term (ES)"),
        (r"\bcadaver\b", "violence term (ES)"),
        (r"\bdegollar\b", "violence term (ES)"),
        (r"\blinchar\b", "violence term (ES)"),
        (r"\bhomicid\w*\b", "violence term (ES)"),
        (r"\bsecuestr\w*\b", "violence term (ES)"),
        (r"\bviolen(cia|to)\b", "violence term (ES)"),
        (r"\bbomba\b", "violence term (ES)"),
        (r"\bexplosivo\b", "violence term (ES)"),
        (r"\bsangre\b", "violence term (ES)"),
        (r"\bdesangrarse\b", "violence term (ES)"),
        (r"\bapuñalar\b", "violence term (ES)"),
        (r"\bestrangular\b", "violence term (ES)"),
        (r"\bincendio\s*provocado\b", "violence term (ES)"),
        # -- Spanish additions: shooting / stabbing / beating --
        (r"\btiroteo\b", "violence term (ES)"),
        (r"\bbalazo\w*\b", "violence term (ES)"),
        (r"\bdisparo\w*\b", "violence term (ES)"),
        (r"\bgolpiza\b", "violence term (ES)"),
        (r"\bpu[ñn]alada\b", "violence term (ES)"),
        (r"\bacuchillar\b", "violence term (ES)"),
        (r"\bnavajazo\b", "violence term (ES)"),
        # -- Spanish additions: methods / outcomes --
        (r"\bdescuartizar\b", "violence term (ES)"),
        (r"\bfusilar\b", "violence term (ES)"),
        (r"\bejecuci[oó]n\b", "violence term (ES)"),
        (r"\bmutilar\b", "violence term (ES)"),
    ],
    # =================================================================
    # SELF_HARM
    # =================================================================
    "SELF_HARM": [
        (r"\bsuicid[ea]l?\b", "self-harm term (EN)"),
        (r"\bselfharm\w*\b", "self-harm term (EN)"),
        (r"\bself\s*harm\w*\b", "self-harm term (EN)"),
        (r"\bself\s*injur\w*\b", "self-harm term (EN)"),
        (r"\bcutmyself\b", "self-harm term (EN)"),
        (r"\bcut\s*myself\b", "self-harm term (EN)"),
        (r"\bkillmyself\b", "self-harm term (EN)"),
        (r"\bkill\s*myself\b", "self-harm term (EN)"),
        # "hurt/harm myself" was MISSING while "kill myself" and "cut myself"
        # were present, so one of the commonest phrasings a distressed child
        # uses fell through to the semantic classifier. Found live 2026-09-09:
        # with the classifier degraded, "I want to hurt myself" returned
        # "I'm having trouble processing that" and logged a classifier error
        # instead of a self-harm incident — so no 988, and no parent alert.
        #
        # Anchored on the reflexive pronoun (myself / my own X) rather than the
        # bare verb: "hurt" is an everyday word, and matching it loosely would
        # refuse "how do muscles get hurt during exercise" or a novel where a
        # character is hurt. The reflexive is what carries the intent.
        (r"\bhurt\s*myself\b", "self-harm term (EN)"),
        (r"\bhurting\s*myself\b", "self-harm term (EN)"),
        (r"\bhurtmyself\b", "self-harm term (EN)"),
        (r"\bharm\s*myself\b", "self-harm term (EN)"),
        (r"\bharming\s*myself\b", "self-harm term (EN)"),
        (r"\binjure\s*myself\b", "self-harm term (EN)"),
        (r"\bend\s*my\s*life\b", "self-harm term (EN)"),
        (r"\biwanttodie\b", "self-harm term (EN)"),
        (r"\bi\s*want\s*to\s*die\b", "self-harm term (EN)"),
        (r"\boverdose\b", "self-harm term (EN)"),
        (r"\bslit\s*(my\s*)?(wrist|throat)\b", "self-harm term (EN)"),
        (r"\bhang\s*myself\b", "self-harm term (EN)"),
        (r"\bjump\s*off\s*(a\s*)?(bridge|building|roof)\b", "self-harm term (EN)"),
        (r"\bend\s*my\s*life\b", "self-harm term (EN)"),
        (r"\bend\s*it\s*all\b", "self-harm term (EN)"),
        (r"\bwant\s*to\s*die\b", "self-harm term (EN)"),
        (r"\bno\s*reason\s*to\s*live\b", "self-harm term (EN)"),
        (r"\bbetter\s*off\s*dead\b", "self-harm term (EN)"),
        (r"\banorexia\b", "self-harm term (EN)"),
        (r"\bbulimia\b", "self-harm term (EN)"),
        (r"\bpurging\b", "self-harm term (EN)"),
        # -- Spanish --
        (r"\bsuicid(io|a|arme|arse)\b", "self-harm term (ES)"),
        (r"\bmatarme\b", "self-harm term (ES)"),
        (r"\bcortarme\b", "self-harm term (ES)"),
        (r"\bquiero\s*morir\b", "self-harm term (ES)"),
        (r"\bquieromorir\b", "self-harm term (ES)"),
        (r"\bautolesi[oó]n\w*\b", "self-harm term (ES)"),
        (r"\bsobredosis\b", "self-harm term (ES)"),
        (r"\bcortarme\s*las?\s*venas?\b", "self-harm term (ES)"),
        (r"\bahorcarme\b", "self-harm term (ES)"),
        (r"\btirarme\s*(de|del)\b", "self-harm term (ES)"),
        (r"\bterminar\s*con\s*todo\b", "self-harm term (ES)"),
        (r"\bno\s*quiero\s*vivir\b", "self-harm term (ES)"),
        (r"\bmejor\s*muert[oa]\b", "self-harm term (ES)"),
        (r"\banorexia\b", "self-harm term (ES)"),
        (r"\bbulimia\b", "self-harm term (ES)"),
        # -- Spanish additions: methods + ideation --
        (r"\bquemar(me|se)\b", "self-harm term (ES)"),
        (r"\b(me\s*)?quiero\s*quemar(me)?\b", "self-harm term (ES)"),
        (r"\benvenenar(me|se)\b", "self-harm term (ES)"),
        (r"\bhacerme\s*da[ñn]o\b", "self-harm term (ES)"),
        (r"\blastimarme\b", "self-harm term (ES)"),
        (r"\bme\s*quiero\s*morir\b", "self-harm term (ES)"),
        (r"\bno\s*sirvo\s*para\s*nada\b", "self-harm term (ES)"),
        (r"\bno\s*vale\s*la\s*pena\s*vivir\b", "self-harm term (ES)"),
    ],
    # =================================================================
    # PROFANITY — general swear words (not slurs, not sexual)
    # =================================================================
    "PROFANITY": [
        (r"\bshit\w*\b", "profanity (EN)"),
        (r"\bbullshit\b", "profanity (EN)"),
        (r"\bass(hole|wipe|hat|face|clown)?\b", "profanity (EN)"),
        (r"\bbitch\w*\b", "profanity (EN)"),
        (r"\bbastard\b", "profanity (EN)"),
        (r"\bdamn(it)?\b", "profanity (EN)"),
        (r"\bhell\b", "profanity (EN)"),
        (r"\bcrap\b", "profanity (EN)"),
        (r"\bpiss\w*\b", "profanity (EN)"),
        (r"\bturd\b", "profanity (EN)"),
        (r"\bdouche\w*\b", "profanity (EN)"),
        (r"\bjackass\b", "profanity (EN)"),
        (r"\bdumbass\b", "profanity (EN)"),
        (r"\bbadass\b", "profanity (EN)"),
        (r"\bwanker\b", "profanity (EN)"),
        (r"\bbollocks\b", "profanity (EN)"),
        (r"\bwank\b", "profanity (EN)"),
        (r"\bsod\s*off\b", "profanity (EN)"),
        (r"\bbugger\b", "profanity (EN)"),
        (r"\barse\b", "profanity (EN)"),
        (r"\bmotherfuck\w*\b", "profanity (EN)"),
        (r"\bstfu\b", "profanity (EN)"),
        (r"\bgtfo\b", "profanity (EN)"),
        (r"\bwtf\b", "profanity (EN)"),
        (r"\bfml\b", "profanity (EN)"),
        # -- Spanish --
        (r"\bmierda\b", "profanity (ES)"),
        (r"\bcarajo\b", "profanity (ES)"),
        (r"\bchinga\w*\b", "profanity (ES)"),
        (r"\bcabr[oó]n\w*\b", "profanity (ES)"),
        (r"\bpinche\b", "profanity (ES)"),
        (r"\bvete\s*a\s*la\s*(mierda|verga|chingada)\b", "profanity (ES)"),
        (r"\bhijo\s*de\s*(puta|perra)\b", "profanity (ES)"),
        (r"\bchingada\s*madre\b", "profanity (ES)"),
        (r"\bla\s*madre\b", "profanity (ES)"),
        (r"\bno\s*mames\b", "profanity (ES)"),
        (r"\bchale\b", "profanity (ES)"),
        (r"\bculero\b", "profanity (ES)"),
        (r"\bpendejad\w*\b", "profanity (ES)"),
        (r"\bmaldito\b", "profanity (ES)"),
        (r"\bmaldita\b", "profanity (ES)"),
        (r"\bjoder\b", "profanity (ES)"),
        (r"\bcoño\b", "profanity (ES)"),
        (r"\bhost?ia\b", "profanity (ES)"),
        (r"\bcojones\b", "profanity (ES)"),
        (r"\bgilipollas\b", "profanity (ES)"),
        (r"\bcapullo\b", "profanity (ES)"),
    ],
    # =================================================================
    # DRUGS
    # =================================================================
    "DRUGS": [
        (r"\bcocaine\b", "drug reference (EN)"),
        (r"\bcoke\s*head\b", "drug reference (EN)"),
        (r"\bcrack\s*head\b", "drug reference (EN)"),
        (r"\bheroin\b", "drug reference (EN)"),
        (r"\bmeth\b", "drug reference (EN)"),
        (r"\bmethamphetamine\b", "drug reference (EN)"),
        (r"\bcrystal\s*meth\b", "drug reference (EN)"),
        (r"\bweed\s*420\b", "drug reference (EN)"),
        (r"\b420\b", "drug reference (EN)"),
        (r"\bblaze\s*it\b", "drug reference (EN)"),
        (r"\bstoner\b", "drug reference (EN)"),
        (r"\bpot\s*head\b", "drug reference (EN)"),
        (r"\bjunkie\b", "drug reference (EN)"),
        (r"\bcrackhead\b", "drug reference (EN)"),
        (r"\blsd\b", "drug reference (EN)"),
        (r"\becstasy\b", "drug reference (EN)"),
        (r"\bmolly\b", "drug reference (EN)"),
        (r"\bketamine\b", "drug reference (EN)"),
        (r"\bfentanyl\b", "drug reference (EN)"),
        (r"\bxanax\b", "drug reference (EN)"),
        (r"\bpercocet\b", "drug reference (EN)"),
        (r"\boxycontin\b", "drug reference (EN)"),
        (r"\badderall\b", "drug reference (EN)"),
        (r"\bshrooms\b", "drug reference (EN)"),
        (r"\bopium\b", "drug reference (EN)"),
        (r"\bcrack\b", "drug reference (EN)"),
        (r"\bdope\b", "drug reference (EN)"),
        (r"\bhigh\s*af\b", "drug reference (EN)"),
        # -- Spanish --
        (r"\bcocaina\b", "drug reference (ES)"),
        (r"\bheroina\b", "drug reference (ES)"),
        (r"\bmetanfetamina\b", "drug reference (ES)"),
        (r"\bmarihuana\b", "drug reference (ES)"),
        (r"\bmota\b", "drug reference (ES)"),
        (r"\byerba\b", "drug reference (ES)"),
        (r"\bporro\b", "drug reference (ES)"),
        (r"\bchurro\b", "drug reference (ES)"),
        (r"\bperico\b", "drug reference (ES)"),
        (r"\bcrista[l]?\b", "drug reference (ES)"),
        (r"\bdrogadicto\b", "drug reference (ES)"),
        (r"\bdrogad[oa]\b", "drug reference (ES)"),
        (r"\bpasti(lla|s)\b", "drug reference (ES)"),
        (r"\btraficante\b", "drug reference (ES)"),
        # -- Spanish additions: street slang --
        (r"\bchiva\b", "drug reference (ES)"),
        (r"\byonqui\b", "drug reference (ES)"),
        (r"\bbasuco\b", "drug reference (ES)"),
        (r"\bfalopa\b", "drug reference (ES)"),
        (r"\bdroga(rse|r|ndo)\b", "drug reference (ES)"),
        (r"\bfum[oó]n\w*\b", "drug reference (ES)"),
        (r"\bgrifo\b", "drug reference (ES)"),
    ],
    # =================================================================
    # DEROGATORY — ableist, demeaning, body-shaming language
    # =================================================================
    "DEROGATORY": [
        (r"\bretard(ed|s)?\b", "ableist slur (EN)"),
        (r"\bspaz(z)?\b", "ableist slur (EN)"),
        (r"\bcripple\b", "ableist slur (EN)"),
        (r"\bimbecile\b", "derogatory (EN)"),
        (r"\bmoron\b", "derogatory (EN)"),
        (r"\bidiot\b", "derogatory (EN)"),
        (r"\bfreak\b", "derogatory (EN)"),
        (r"\bloser\b", "derogatory (EN)"),
        (r"\bpathetic\b", "derogatory (EN)"),
        (r"\bdegen(erate)?\b", "derogatory (EN)"),
        (r"\bscum\b", "derogatory (EN)"),
        (r"\bscumbag\b", "derogatory (EN)"),
        (r"\bvermin\b", "derogatory (EN)"),
        (r"\bsubhuman\b", "derogatory (EN)"),
        (r"\blard\s*ass\b", "body shaming (EN)"),
        (r"\bfatty\b", "body shaming (EN)"),
        (r"\bfatass\b", "body shaming (EN)"),
        (r"\bugly\s*ass\b", "body shaming (EN)"),
        (r"\bsociopath\b", "derogatory (EN)"),
        (r"\bpsycho(path)?\b", "derogatory (EN)"),
        (r"\blunatic\b", "derogatory (EN)"),
        (r"\bmental\s*case\b", "derogatory (EN)"),
        (r"\bnutcase\b", "derogatory (EN)"),
        (r"\bnutjob\b", "derogatory (EN)"),
        (r"\bcrazy\b", "derogatory (EN)"),
        (r"\binsane\b", "derogatory (EN)"),
        (r"\bweeb\b", "derogatory (EN)"),
        (r"\bneckbeard\b", "derogatory (EN)"),
        (r"\bvirgin\b", "derogatory (EN)"),
        (r"\btrigger(ed|ing)\b", "derogatory (EN)"),
        (r"\bsnowflake\b", "derogatory (EN)"),
        (r"\blibtard\b", "derogatory (EN)"),
        (r"\bcuck\b", "derogatory (EN)"),
        (r"\bsoyboy\b", "derogatory (EN)"),
        # -- Spanish --
        (r"\bretrasad[oa]\b", "ableist slur (ES)"),
        (r"\bpendej[oa]\b", "profanity (ES)"),
        (r"\bput[oa]\b", "profanity (ES)"),
        (r"\best[uú]pid[oa]\b", "derogatory (ES)"),
        (r"\bidiota\b", "derogatory (ES)"),
        (r"\bimbecil\b", "derogatory (ES)"),
        (r"\btarad[oa]\b", "derogatory (ES)"),
        (r"\bmens[oa]\b", "derogatory (ES)"),
        (r"\bton?t[oa]\b", "derogatory (ES)"),
        (r"\bbab?os[oa]\b", "derogatory (ES)"),
        (r"\bburr[oa]\b", "derogatory (ES)"),
        (r"\bbrut[oa]\b", "derogatory (ES)"),
        (r"\binutil\b", "derogatory (ES)"),
        (r"\bbasura\b", "derogatory (ES)"),
        (r"\bescoria\b", "derogatory (ES)"),
        (r"\benferm[oa]\s*mental\b", "derogatory (ES)"),
        (r"\bloc[oa]\b", "derogatory (ES)"),
        (r"\bdemente\b", "derogatory (ES)"),
        (r"\bgord[oa]\s*(asqueros[oa]|cerdo)?\b", "body shaming (ES)"),
        (r"\bcerdo\b", "derogatory (ES)"),
        (r"\bfe[oa]\b", "body shaming (ES)"),
        (r"\bmuert[oa]\s*de\s*hambre\b", "derogatory (ES)"),
        (r"\barrastrad[oa]\b", "derogatory (ES)"),
        (r"\bcorrient[oe]\b", "derogatory (ES)"),
        # -- Spanish additions: ableist + regional --
        (r"\bsubnormal\b", "ableist slur (ES)"),
        (r"\bhuev[oó]n\w*\b", "derogatory (ES)"),
        (r"\bcerote\b", "derogatory (ES)"),
        (r"\banormal\b", "ableist slur (ES)"),
    ],
}
