"""SUBSTR_CHECKS — substring evasion checks.

Extracted verbatim from the former safety/patterns.py.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

# ============================================================================
# Substring evasion checks (matched against letters-only normalised form)
# ============================================================================

SUBSTR_CHECKS: Dict[str, List[Tuple[str, str]]] = {
    "HATE_SPEECH": [
        ("nigger", "racial slur"),
        ("nigga", "racial slur"),
        ("nigg", "racial slur"),
        ("coon", "racial slur"),
        ("darkie", "racial slur"),
        ("jigaboo", "racial slur"),
        ("porchmonkey", "racial slur"),
        ("spearchucker", "racial slur"),
        ("faggot", "orientation slur"),
        ("fagot", "orientation slur"),
        ("dyke", "orientation slur"),
        ("tranny", "transphobic slur"),
        ("shemale", "transphobic slur"),
        ("kike", "antisemitic slur"),
        ("wetback", "ethnic slur"),
        ("beaner", "ethnic slur"),
        ("chink", "ethnic slur"),
        ("gook", "ethnic slur"),
        ("towelhead", "ethnic slur"),
        ("raghead", "ethnic slur"),
        ("spic", "ethnic slur"),
        ("redskin", "ethnic slur"),
        ("maricon", "orientation slur (ES)"),
        ("mayate", "racial slur (ES)"),
        ("prieto", "racial slur (ES)"),
        ("nazi", "Nazi reference"),
        ("neonazi", "Nazi reference"),
        ("hitler", "Nazi reference"),
        ("hltler", "Nazi reference (leet)"),
        ("whitepower", "supremacist term"),
        ("whitesuprem", "supremacist term"),
        ("aryanrace", "supremacist term"),
        ("kuklux", "hate group"),
        ("skinhead", "hate group"),
    ],
    "SEXUAL_CONTENT": [
        ("porn", "explicit term"),
        ("hentai", "explicit term"),
        ("cocksucker", "explicit term"),
        ("blowjob", "explicit term"),
        ("handjob", "explicit term"),
        ("gangbang", "explicit term"),
        ("threesome", "explicit term"),
        ("deepthroat", "explicit term"),
        ("bukkake", "explicit term"),
        ("creampie", "explicit term"),
        ("masturbat", "explicit term"),
        ("ejaculat", "explicit term"),
        ("cumshot", "explicit term"),
        ("milf", "explicit term"),
        ("dilf", "explicit term"),
        ("rape", "explicit term"),
        ("rapist", "explicit term"),
        ("molest", "explicit term"),
        ("pedophil", "explicit term"),
        ("pedofil", "explicit term (ES)"),
        ("prostitu", "explicit term"),
        ("hooker", "explicit term"),
        ("stripper", "explicit term"),
        ("sexslave", "explicit term"),
        ("violador", "explicit term (ES)"),
        ("violacion", "explicit term (ES)"),
        ("ramera", "explicit term (ES)"),
        ("zorra", "explicit term (ES)"),
    ],
    "VIOLENCE": [
        ("schoolshoot", "violence term"),
        ("massmurder", "violence term"),
        ("massshoot", "violence term"),
        ("serialkill", "violence term"),
        ("killer", "violence term"),
        ("murder", "violence term"),
        ("genocide", "violence term"),
        ("terrorist", "violence term"),
        ("behead", "violence term"),
        ("dismember", "violence term"),
        ("mutilat", "violence term"),
        ("slaughter", "violence term"),
        ("massacre", "violence term"),
        ("asesino", "violence term (ES)"),
        ("sicario", "violence term (ES)"),
        ("narco", "violence term (ES)"),
        ("decapitar", "violence term (ES)"),
        ("degollar", "violence term (ES)"),
        ("tiroteo", "violence term (ES)"),
        ("golpiza", "violence term (ES)"),
        ("descuartizar", "violence term (ES)"),
        ("fusilar", "violence term (ES)"),
        ("acuchillar", "violence term (ES)"),
        ("navajazo", "violence term (ES)"),
    ],
    "SELF_HARM": [
        ("suicide", "self-harm term"),
        ("selfharm", "self-harm term"),
        ("selfinjur", "self-harm term"),
        ("killmyself", "self-harm term"),
        ("iwanttodie", "self-harm term"),
        ("cutmyself", "self-harm term"),
        ("endmylife", "self-harm term"),
        ("enditall", "self-harm term"),
        ("betteroffdead", "self-harm term"),
        ("slitmywrist", "self-harm term"),
        ("hangmyself", "self-harm term"),
        ("quieromorir", "self-harm term (ES)"),
        ("matarme", "self-harm term (ES)"),
        ("cortarme", "self-harm term (ES)"),
        ("autolesion", "self-harm term (ES)"),
        ("suicidio", "self-harm term (ES)"),
        ("ahorcarme", "self-harm term (ES)"),
        ("quemarme", "self-harm term (ES)"),
        ("envenenarme", "self-harm term (ES)"),
        ("lastimarme", "self-harm term (ES)"),
        ("hacermedano", "self-harm term (ES)"),
        ("nosirvoparanada", "self-harm term (ES)"),
    ],
    "PROFANITY": [
        ("shit", "profanity"),
        ("motherfuck", "profanity"),
        ("bullshit", "profanity"),
        ("asshole", "profanity"),
        ("asswipe", "profanity"),
        ("asshat", "profanity"),
        ("assface", "profanity"),
        ("dumbass", "profanity"),
        ("jackass", "profanity"),
        ("douchebag", "profanity"),
        ("bitch", "profanity"),
        ("bastard", "profanity"),
        ("wanker", "profanity"),
        ("bollocks", "profanity"),
        ("bugger", "profanity"),
        ("piss", "profanity"),
        ("hijodeputa", "profanity (ES)"),
        ("hijodeperra", "profanity (ES)"),
        ("chingadamadre", "profanity (ES)"),
        ("gilipollas", "profanity (ES)"),
        ("mierda", "profanity (ES)"),
        ("cabron", "profanity (ES)"),
        ("culero", "profanity (ES)"),
        ("cojones", "profanity (ES)"),
    ],
    "DRUGS": [
        ("cocaine", "drug reference"),
        ("cocaina", "drug reference (ES)"),
        ("heroin", "drug reference"),
        ("heroina", "drug reference (ES)"),
        ("methamphetamine", "drug reference"),
        ("metanfetamina", "drug reference (ES)"),
        ("crystalmeth", "drug reference"),
        ("crackhead", "drug reference"),
        ("junkie", "drug reference"),
        ("fentanyl", "drug reference"),
        ("oxycontin", "drug reference"),
        ("drogadicto", "drug reference (ES)"),
        ("traficante", "drug reference (ES)"),
        ("chiva", "drug reference (ES)"),
        ("yonqui", "drug reference (ES)"),
        ("basuco", "drug reference (ES)"),
        ("falopa", "drug reference (ES)"),
        ("drogar", "drug reference (ES)"),
    ],
    "DEROGATORY": [
        ("retard", "ableist slur"),
        ("retarded", "ableist slur"),
        ("subhuman", "derogatory"),
        ("scumbag", "derogatory"),
        ("libtard", "derogatory"),
        ("soyboy", "derogatory"),
        ("neckbeard", "derogatory"),
        ("nutjob", "derogatory"),
        ("nutcase", "derogatory"),
        ("fatass", "body shaming"),
        ("lardass", "body shaming"),
        ("retrasado", "ableist slur (ES)"),
        ("escoria", "derogatory (ES)"),
        ("subnormal", "ableist slur (ES)"),
        ("huevon", "derogatory (ES)"),
        ("cerote", "derogatory (ES)"),
    ],
}
